### ISSUE TITLE
doctest fails on 2 examples

### ISSUE THREAD

**Issue by bennokr** [heatherleaf/MCFParser.py#1]
Running `python MCFParser.py` gives the following output:

```
**********************************************************************
File "MCFParser.py", line 85, in __main__.Parser
Failed example:
    parser.print_grammar_statistics()
Expected:
    Grammar statistics          ||
    -------------------|--------:|
    Nr. terminals      |       2 |
    Nr. nonterminals   |       2 |
    Nr. nonterm-const. |       3 |
    Nr. grammar rules  |       3 |
    Nr. constituents   |       5 |
    Nr. const. lengths |      12 |
    Nr. empty const.   |       0 |
    Nr. leftc. pairs   |       4 |
    Nr. lcword. pairs  |       2 |
Got:
    Grammar statistics          ||
    -------------------|--------:|
    Nr. terminals      |       4 |
    Nr. nonterminals   |       2 |
    Nr. nonterm-const. |       3 |
    Nr. grammar rules  |       3 |
    Epsilon-free       |    True |
    Nr. constituents   |       5 |
    Nr. const. lengths |      12 |
    Nr. empty const.   |       0 |
    Nr. leftc. pairs   |       4 |
    Nr. lcword. pairs  |       2 |
**********************************************************************
File "MCFParser.py", line 98, in __main__.Parser
Failed example:
    parser.print_parse_statistics()
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.Parser[6]>", line 1, in <module>
        parser.print_parse_statistics()
      File "MCFParser.py", line 304, in print_parse_statistics
        print "%-11s|" % (hdr,) + "".join("%9s |" % (stat.get(key, "--"),) for key in statkeys)
      File "MCFParser.py", line 304, in <genexpr>
        print "%-11s|" % (hdr,) + "".join("%9s |" % (stat.get(key, "--"),) for key in statkeys)
    TypeError: unhashable type: 'set'
**********************************************************************
1 items had failures:
   2 of   7 in __main__.Parser
***Test Failed*** 2 failures.
```

**Comment by heatherleaf** [comment]
Finally fixed!
